### ISSUE TITLE
Large projects are too large to send to playground!

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/paper-land#188]
@terracoda encountered an error that looks like this:

::1 - POST /api/spaces/ts-creator-tests/programs/set HTTP/1.1 413 7017 - 1.486 ms
PayloadTooLargeError: request entity too large
    at readStream (C:\Users\Jesse\Documents\Development\phetsims\paper-land\node_modules\raw-body\index.js:156:17)
    at getRawBody (C:\Users\Jesse\Documents\Development\phetsims\paper-land\node_modules\raw-body\index.js:109:12)
    at read (C:\Users\Jesse\Documents\Development\phetsims\paper-land\node_modules\body-parser\lib\read.js:79:3)
    at jsonParser (C:\Users\Jesse\Documents\Development\phetsims\paper-land\node

Yikes! Lets figure out a solution.

**Comment by jessegreenberg** [comment]
Saving the project to JSON seems OK thankfully. But the operation to insert programs into the table is failing.

**Comment by jessegreenberg** [comment]
OK, programs are now inserted one at a time from Creator and that reduces the payload. I tested with several projects including a copy of @terracoda's where we first saw this. Fix was merged into main. Closing.
