### ISSUE TITLE
Creator crashes when duplicating card with array component in bf-tests > twenty-card

### ISSUE THREAD

**Issue by brettfiedler** [phetsims/paper-land#236]
Try duplicating 2 Diamond. Crashes with:

```
phet-lib-main.js:32 Uncaught Error: Assertion failed: Reference component must be in the list of model components
    at window.assertions.assertFunction (phet-lib-main.js:32:51)
    at eval (ViewComponent.js:83:17)
    at Array.forEach (<anonymous>)
    at DescriptionViewComponent.setReferenceComponentNames (ViewComponent.js:82:29)
    at new ViewComponent (ViewComponent.js:47:10)
    at new DescriptionViewComponent (DescriptionViewComponent.js:11:5)
    at DescriptionViewComponent.fromStateObject (DescriptionViewComponent.js:19:12)
    at eval (ProgramViewContainer.js:165:100)
    at Array.forEach (<anonymous>)
    at ProgramViewContainer.load (ProgramViewContainer.js:164:22)
```

**Comment by jessegreenberg** [comment]
Also, program duplication involved a project with an array component.

**Comment by brettfiedler** [comment]
Ah, I think this actually might have to do with the reference feature, and may not involve the array component (though that may have other problems).

Ran into this in a project (bf-tests > multimodal-book) when trying to duplicate a project. One of the components (coverText) in the views is a reference instead of dependency. Crashed Creator.

![image](https://github.com/phetsims/paper-land/assets/47331395/8b28d51e-e748-491d-8571-ccbfee85cb56)

![image](https://github.com/phetsims/paper-land/assets/47331395/245a3a2b-f2c9-40f1-bd01-e61340b21420)

Can reproduce easily by duplicating the lone program.

**Comment by jessegreenberg** [comment]
OK I think this should be fixed in the dev branch. Unit tests coming up.

**Comment by jessegreenberg** [comment]
OK, I merged this into the main branch. I tested by copying a program with a reference connection in a test project. I added some unit tests for this case. Then I created a copy of bf-tests/twenty-card jg-tests and copied the 2 Diamond program and have a reasonable looking copy with no crash.

Closing.
