### ISSUE TITLE
Camera not loading properly

### ISSUE THREAD

**Issue by terracoda** [phetsims/paper-land#58]
While testing with Brett this morning, I got these console errors.

Brett thought it might have something to do with the default space (bf-tests) that was loading. Not sure if he still thinks that.

Canvas2D: Multiple readback operations using getImageData are faster with the willReadFrequently attribute set to true. See: <URL>
opencv.js:20 Uncaught abort("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 2147418112, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime, or (3) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 ") at Error
    at jsStackTrace (http://localhost:3000/opencv.js:20:12687)
    at stackTrace (http://localhost:3000/opencv.js:20:12858)
    at abort (http://localhost:3000/opencv.js:20:262876)
    at abortOnCannotGrowMemory (http://localhost:3000/opencv.js:20:13923)
    at http://localhost:3000/opencv_js.wasm:wasm-function[7559]:0x4858d5
    at http://localhost:3000/opencv_js.wasm:wasm-function[6763]:0x445ccf
    at http://localhost:3000/opencv_js.wasm:wasm-function[6768]:0x4479c5
    at http://localhost:3000/opencv_js.wasm:wasm-function[6769]:0x447b60
    at http://localhost:3000/opencv_js.wasm:wasm-function[893]:0x27246
    at http://localhost:3000/opencv_js.wasm:wasm-function[1481]:0xa611f
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.
opencv.js:20 Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 2147418112, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime, or (3) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0
opencv.js:20 Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 2147418112, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime, or (3) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0

**Comment by terracoda** [comment]
Now (14:00) I just get a black screen. It looks like I am missing some react stuff?

Uncaught Error: Cannot find module 'bootstrap-switch-button-react'
    at webpackMissingModule (CameraControls.js:8:50)
    at eval (CameraControls.js:8:154)
    at ./client/camera/CameraControls.js (camera.js:228:1)
    at __webpack_require__ (camera.js:8952:42)
    at eval (CameraMain.js:15:76)
    at ./client/camera/CameraMain.js (camera.js:239:1)
    at __webpack_require__ (camera.js:8952:42)
    at eval (entry.js:9:69)
    at ./client/camera/entry.js (camera.js:305:1)
    at __webpack_require__ (camera.js:8952:42)

**Comment by terracoda** [comment]
I can't do any testing or review until the system can load.

**Comment by terracoda** [comment]
@jessegreenberg and I met, then @jbphet and I met, and it looks like I need a better webcam. @jbphet rolled back the camera controls, so I can now at least load the system. I just can't use it with real papers.
